image: debian:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
build:
  stage: build
  before_script:
    - git submodule sync --recursive
    - apt-get update -qq
    - apt-get install -qq make cmake gcc-8
  script:
    - mkdir build && cd build && cmake ../ && make
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/bin/Sc2LadderServer